version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .dockervenv:/app/.venv
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'demo'
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # 絶対パスに変更
    depends_on:
      - app
  ngrok:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    volumes:
      - ./ngrok.yml:/ngrok/ngrok.yml  # ngrok.yml ファイルをマウント
    command: ngrok start --config /ngrok/ngrok.yml  # ngrok 起動時に設定ファイルを指定
    depends_on:
      - nginx
