services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - "8000:8000"
    env_file:
      - .env  # 環境変数を.envファイルから読み込む
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'demo'
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "127.0.0.1:33306:3306"  # ローカルホストにバインドして外部からのアクセスを防ぐ
    tty: true
volumes:
  mysql_data: